apiVersion: v1
kind: PersistentVolume
metadata:
  name: podmanager-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/c/Users/Lemma/Downloads/.kube"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podmanager-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi