
apiVersion: v1
kind: Service
metadata:
  name: miniflask-service
spec:
  selector:
    app: miniflask
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: miniflask
  labels:
    app: miniflask
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: miniflask
      image: docker.io/lemmav/miniflask
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -c 
      - "gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server"
      ports:
      - containerPort: 8000
      volumeMounts:
      - mountPath: "/dbdir"
        name: task-pv-storage
    - name: minicheckdb
      image: docker.io/lemmav/minicheckdb
      imagePullPolicy: IfNotPresent
      volumeMounts:
      # - mountPath: "/dbdir"
      - mountPath: "/checkdb"
        name: task-pv-storage


        